guestbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^/', include('wordfib.urls', namespace='wordfib')),
    url(r'^/admin/', include(admin.site.urls)),
    url(r'^$', include('wordfib.urls', namespace='wordfib')),
)

wordfib/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'wordfib.views.home_page', name='home'),
    url(r'^from_def/', 'wordfib.views.home_page', {'from_def': True}, name='from_def'),
    url(r'^blank_name', 'wordfib.views.home_page', {'name_error': True}, name='blank_name'),
    url(r'^blank_choice', 'wordfib.views.home_page', {'choice_error': True}, name='blank_choice'),
    url(r'^self_voter', 'wordfib.views.home_page', {'self_error': True}, name='self_voter'),
    url(r'^add_another/', 'wordfib.views.add_another', name='add_another'),
    url(r'^add_yet_another/', 'wordfib.views.add_another', {'pop_again': True}, name='add_yet_another'),
    url(r'^from_add/', 'wordfib.views.add_def', {'from_add_another': True}, name='from_add'),
    url(r'^scoreboard/', 'wordfib.views.scoreboard', name='scoreboard'),
    url(r'^vote/', 'wordfib.views.vote', name='vote'),
    url(r'^add_def/', 'wordfib.views.add_def', name='add_def'),
)

wordfib/models.py
from django.db import models

class WordAndTrue(models.Model):
    word = models.CharField(max_length=50)
    real_definition = models.CharField(max_length=700, blank=True, null=True)
    definition = models.CharField(max_length=700)
    def __str__(self):
        return self.word

class FakeDefinitions(models.Model):
    real_word = models.ForeignKey(WordAndTrue)
    fake_definition = models.CharField(max_length=700, blank=True, null=True)
    definition = models.CharField(max_length=700)
    votes = models.IntegerField(default=0)
    author = models.CharField(max_length=20)
    def __str__(self):
        return self.author

    def score(self):
        return self.votes
    
    def fake_def(self):
        return self.fake_definition 

class CorrectGuess(models.Model):
    user = models.CharField(max_length=20, unique=True)
    score = models.IntegerField(default=0)
    def __str__(self):
        return self.user

    def score_from_correct(self):
        return self.score

wordfib/views.py
from django.shortcuts import render, redirect
from wordfib.models import WordAndTrue, FakeDefinitions, CorrectGuess
from random import randint, shuffle, choice
from django.core.exceptions import ValidationError

# deploys game with random word and definitions
def home_page(request, from_def=False, name_error=False, def_error=False, choice_error=False, self_error=False):
    rand_word = choice(WordAndTrue.objects.all())
    # word needs at least 2 fake definitions to be displayed
    while rand_word.fakedefinitions_set.count() < 2:
        rand_word = choice(WordAndTrue.objects.all())

    def_list = []
    for defs in (rand_word.fakedefinitions_set.all()):
        def_list.append(defs)

    # include real definition
    def_list.append(rand_word)
    shuffle(def_list)

    # checks to see if user is coming from creation page
    # also handles form validation...kinda hackish I know
    if from_def:
        return render(request, 'home_after_def.html', {'rand_word': rand_word, 'def_list': def_list})
    elif name_error:
        return render(request, 'home.html', {'rand_word': rand_word, 'def_list': def_list, 'error': 'Enter a username!!'})
    elif choice_error:
        return render(request, 'home.html', {'rand_word': rand_word, 'def_list': def_list, 'error': 'Select a definition!'})
    elif def_error:
        return render(request, 'home.html', {'rand_word': rand_word, 'def_list': def_list, 'error': 'Enter a definition!'})
    elif self_error:
        return render(request, 'home.html', {'rand_word': rand_word, 'def_list': def_list, 'error': 'Ah ah ah, bad boy! Don\'t vote on definitions YOU created!'})
    else:
        return render(request, 'home.html', {'rand_word': rand_word, 'def_list': def_list})

# handles voting on the provided word
def vote(request):
    # grab a random word for player to write a fake def.
    rand_word = choice(WordAndTrue.objects.all())
    
    # requires word to have fewer than 3 definitions.
    while rand_word.fakedefinitions_set.count() >= 2:
        rand_word = choice(WordAndTrue.objects.all())

    # enforce lower-case and alpha only
    lower_user = request.POST['username'].lower()
    lower_user = lower_user.lower()
    lower_user = ''.join(c for c in lower_user if c.islower())
    if len(lower_user) == 0:
        return redirect('wordfib:blank_name')
    
    # check if user has already correctly guessed a def.
    user = CorrectGuess.objects.filter(user=lower_user)

    # primary key number of multiple-choice selection
    u_choice = request.POST.get('choice', False)
    if u_choice == False:
        return redirect('wordfib:blank_choice')

    choice_list = []
    choice_list = u_choice.split('-')
    choice_type = choice_list[0]
    choice_uid = choice_list[1]

    # if not already a user, create the user
    if user.count() == 0:
        user = CorrectGuess.objects.create(user=lower_user)
        user.save()
        user.full_clean()
    else:
        user = CorrectGuess.objects.get(user=lower_user)
        
        
    # Handle the scoring and responses of correct vs incorrect guesses
    sent_word = request.POST['word']
    true_def = WordAndTrue.objects.get(word=sent_word)

    #if WordAndTrue.objects.filter(pk=uid).count() == 0:
    #if true_def.id != int(uid):
    if choice_type == "FakeDefinitions":
        fake_def = FakeDefinitions.objects.get(pk=choice_uid)

        # Disallows someone voting on their own definition
        if fake_def.author == lower_user:
            return redirect('wordfib:self_voter')

        fake_def.votes += 2
        fake_def.save()
        current_score = user.score
        get_fake = FakeDefinitions.objects.filter(author=lower_user)
        if get_fake.count() != 0:
            for defs in get_fake:
                current_score += defs.votes 

        return render(request, 'wordfibbd.html', {'author': fake_def, 'current_score': current_score, 'user': user, 'rand_word': rand_word })
    else:
        real_def = WordAndTrue.objects.get(pk=choice_uid)
        user.score += 1
        user.save()
        current_score = user.score
        fake_def = FakeDefinitions.objects.filter(author=lower_user)

        if fake_def.count() != 0:
            for defs in fake_def:
                current_score += defs.votes 
    
        return render(request, 'congrats.html', {'real_def': real_def, 'user': user, 'current_score': current_score, 'rand_word': rand_word}) 

# adds definition to database
def add_def(request, from_add_another=False):
    word = WordAndTrue.objects.get(word=request.POST['word'])

    # tries to reduce/homegenize punctuation and capitilization to reduce
    # some perfect formatting giving away the real definition
    u_def = request.POST['definition'].lower()
    u_def = u_def.rstrip()

    while u_def.startswith(" "):
        u_def = u_def[1:]

    u_def = ''.join(c for c in u_def if c.islower() or c.isdigit() or c == ' ' or c == ',' or c == "'" or c == '.') 

    if len(u_def) == 0:
        return render(request, "create_def.html", {'n_user': request.POST['user'], 'rand_word': request.POST['word']} )

    if u_def[-1] != '.':
        u_def += '.'

    new_def = word.fakedefinitions_set.create(author=request.POST['user'], definition=u_def)

    new_def.save()
    new_def.full_clean()

    if from_add_another:
        return redirect('wordfib:add_yet_another')
    else:
        return redirect('wordfib:from_def')

def scoreboard(request):
    # declare lists for table data
    user_list = []
    cg_score = []
    wf_votes = []
    total_score = []

    # collect user and collect score from correct guesses for each user
    for user in CorrectGuess.objects.all():
        user_list.append(user.user)
        cg_score.append(user.score) 

    # collect score from wordfibbing others for each user
    for author in user_list:
        f_temp = 0
        f_score = FakeDefinitions.objects.filter(author=author) 
        # this collects votes from all definitions created
        for f_def in f_score:
            f_temp += f_def.votes

        wf_votes.append(f_temp)
    

    
    # list comprehension to calculate total votes
    total_score = [(wf + cg) for wf, cg in zip(wf_votes, cg_score)]

    #list comprehension to create lists for each user
    sb_set = [[a, b, c, d] for a, b, c, d in zip(user_list, wf_votes, cg_score, total_score)]

    return render(request, 'scoreboard.html', {'sb_set': sb_set})
     
def add_another(request, pop_again=False):
    
    # grab a random word for player to write a fake def.
    rand_word = choice(WordAndTrue.objects.all())

    while rand_word.fakedefinitions_set.count() >= 2:
        rand_word = choice(WordAndTrue.objects.all())

    thanks_list = ['Thank you very much!', 'Muchas Gracias!', 'Baie Dankie!', 'Merci Beaucoup!', 'Domo Arigato!']
    shuffle(thanks_list)
    thanks = thanks_list[0]

    return render(request, 'populate.html', {'rand_word': rand_word, 'pop_again': pop_again, 'thanks': thanks})

wordfib/templates/congrats.html
{% include 'header.html' %}
        <div>
            <p>Good Job {{ user.user }}! You guessed the correct definition for {{ real_def.word }}!</p>    
            <p> Your current score is {{ current_score }}.</p>
            <p>You can get more points wordfibbing someone else by writing a fake definition!</p>
        </div>
{% include 'word_def_footer.html' %}

wordfib/templates/create_def.html
{% include 'header.html' %}
        <div>
            <p>Create a definition for the word,</p>
            <h2>{{ rand_word }}:</h2>
            <form action="{% url 'wordfib:add_def' %}" method="post">
            {% csrf_token %}
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"><span>
                    <span class="sr-only">Error:</span>
                     You didn't enter a definition!
                </div>
                <input type="hidden" value="{{ n_user }}" name="user"/>
                <input type="hidden" value="{{ rand_word }}" name="word"/>
                <textarea  id="inputHelpBlock" class="form-control" rows="4" cols="50" name="definition" autofocus placeholder="Enter definition here"></textarea>
                <span id="helpBlock" class="help-block"><ol>
                    <li>You can make an obviously fake, yet incredibly humorous definition, but realize that this approach should be used as sparingly as salt and sarcasm.</li>
                    <li>A dry and convincing definition will net you good points, but may be boring.</li>
                    <li>A subtle combination of #1 and #2 will entertain but still win votes!</li></span>
                </br>
                <p>
                    <input type="submit" class="btn btn-primary btn-lg" value="Enter Definition">
                </p>
            </form>
        </div>
    </div>
    </div>
    </body>
</html>

wordfib/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Wordfib</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">
    <link href="static/bootstrap/fonts/MyUnderwood.ttf" rel="stylesheet" media="screen">
    <meta name="robots" content="noindex">
</head>
<body>
<div class="container">
<div class="text-center jumbotron">
    <ul class="nav nav-pills nav-justified">
        <li role="presentation" ><a href="{% url 'wordfib:home' %}"><p>-New Word-</p></a></li>
        <li role="presentation"><a href="{% url 'wordfib:scoreboard' %}"><p>-Scoreboard-</p></a></li>
        <li role="presentation" ><a href="{% url 'wordfib:add_another' %}"><p>-Add a Definition-</p></a></li>
    </ul>
    <h1><a href="{% url 'wordfib:home'%}">WORDFIB</a></h1>
    </br>

wordfib/templates/home.html
{% include 'header.html' %}
{% load check_type %}
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"><span>
            <span class="sr-only">Error:</span>
            {{ error }}
        </div>
        {% endif %}
    <div class="page-header">
        <h2>{{ rand_word }}:</h2>
    </div>
    <div>
        <form action="{% url 'wordfib:vote' %}" method="post">
        <fieldset>
        {% csrf_token %}
            <input type="hidden" value="{{ rand_word }}" name="word"/>
            <ul class="list-group">
            {% for def in def_list %}
                <li class="list-group-item">
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ def | to_class_name }}-{{ def.id }}"/>
                    <label for="choice{{ forloop.counter }}">{{ def.definition }}</label>
                </li></br>
            {% endfor %}
            </ul>
            {% if error %}
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"><span>
                <span class="sr-only">Error:</span>
                {{ error }}
            </div>
            {% endif %}
            <div class="row">
                <div class="col-xs-4 col-xs-offset-4">
                <input type="text" id="inputHelpBlock" style="text-align:center" class="form-control" name="username" placeholder="lfirst"/>
                <span id="helpBlock" class="help-block">Use the same username every time. Simply your last initial immediately followed by your first name, e.g. "wgeorge"</span>
                </div>
            </div>
            <div>
                <input type="submit" class="btn btn-primary btn-lg" value="Submit Guess"/>
            </div>
        </fieldset>
        </form>
    </div>
</div>
</div>
</body>
</html>

wordfib/templates/home_after_def.html
{% include 'header.html' %}
    <div>
        <p>Thanks for submitting your definition!</p>
        <p>You can play again if you like!</p>
        <p>Just don't vote on your own fake definitions if encountered!!!</p>
    </div>
        {% csrf_token %}
    <div class="page-header">
        <h2>{{ rand_word }}:</h2>
    </div>
    <div>
        <form action="{% url 'wordfib:vote' %}" method="post">
        <fieldset>
        {% csrf_token %}
            <ul class="list-group">
            {% for def in def_list %}
                <li class="list-group-item">
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ def.id }}"/>
                    <label for="choice{{ forloop.counter }}">{{ def.definition }}</label>
                </li></br>
            {% endfor %}
            </ul>
            <div class="row">
                <div class="col-xs-4 col-xs-offset-4">
                <input type="text" id="inputHelpBlock" style="text-align:center" class="form-control" name="username" placeholder="lfirst"/>
                <span id="helpBlock" class="help-block">Use the same username every time. Simply your last initial immediately followed by your first name, e.g. "wgeorge"</span>
                </div>
            </div>
            <div>
                <input type="submit" class="btn btn-primary btn-lg" value="Submit Guess"/>
            </div>
        </fieldset>
        </form>
    </div>
    <div>
        <a href="{% url 'wordfib:scoreboard' %}">Check out the Scoreboard</a>
    </div>
</div>
</div>
</body>

</html>

wordfib/templates/populate.html
{% include 'header.html' %}
        {% if pop_again %}
        <div>
                <p>{{ thanks }}</p> 
                <p>You may define another if you like!</p>
        </div>
        {% endif %}
        <div>
            <p>Thanks for helping me populate some false definitions for this Wordfib game. The point is to be convincing and to fool others into voting on a false definition. (a minimal version of a <a href="http://en.wikipedia.org/wiki/Balderdash">Balderdash</a> clone)</p>
            <p>This game is not meant to stay online, it actually is intended for my local home network only, this is just testing, and will be taken down in a short amount of time.</p>
            <p>You can make an obviously fake, yet incredibly humorous definition, but realize that this approach should be used as sparingly as salt and sarcasm, lest the real definition be too obvious.</p>
            <p>A dry and convincing definition will cause confusion and create a greater challenge, but may be boring.</p>
            <p>A subtle combination of the two will entertain but still create a head-scratcher.</p>
        </br>
        </div>
        <div>
            <h2>{{ rand_word }}:</h2>
            </br>
            <fieldset>
            <form action="{% url 'wordfib:from_add' %}" method="post">
            {% csrf_token %}
                <input type="hidden" value="{{ rand_word }}" name="word"/>
                <textarea id="inputHelpBlock" class="form-control"  rows="4" cols="50" name="definition" placeholder="Enter definition here"></textarea>
                <span id="helpBlock" class="help-block"><ol>
                    <p>Commas, apostrophes, and periods are the only punctuation allowed.</p></span>
                </br>
            <div class="row">
                <div class="col-xs-4 col-xs-offset-4">
                <input type="text" id="inputHelpBlock" style="text-align:center" class="form-control" name="user" placeholder="lfirst"/>
                <span id="helpBlock" class="help-block">Use the same username every time. Simply your last initial immediately followed by your first name, e.g. "wgeorge"</span>
                </div>
            </div>
                <div class="text-center">
                    <!--<input type="hidden" name="user" value="anonymous"/>-->
                    <p><input type="submit" class="btn btn-primary btn-lg" value="Enter Definition"></p>
                </div>
            </form>
            </fieldset>
        </div>
    </div>
    </div>
    </body>
</html>

wordfib/templates/scoreboard.html
{% include 'header.html' %}
       <div class="panel panel-default">
           <div class="panel-heading"><h2>Scoreboard</h2></div>
           <div class="panel-body">
               <p>Scores are broken out into points earned by wordfibbing others and points earned by guessing the correct definition</p>
       </div>
           <table id="score-table" class="table table-striped table-hover">
               <thead style="display:table-header-group">
                  <tr>
                       <th class="header-center">User</th>
                       <th class="header-center">Wordfib Points</th>
                       <th class="header-center">Correct Guess Points</th>
                       <th class="header-center">Total Score</th>
                  </tr>
               </thead>
               <tbody>
               {% for rec in sb_set %}
               <tr>
                   {% for data in rec %}
                       <td>{{ data }}</td>
                   {% endfor %}
               </tr>
               {% endfor %}
               </tbody>
           </table> 
       </div> 
        <div class="tilt">
            <p>Guess Correctly: 1 point</p>
            <p>Wordfib Someone: 2 points</p>
        </div>
    </div>
    </div>
    </body>
</html>

wordfib/templates/word_def_footer.html
        <div>
            <p>Create a definition for the word,</p>
            <h2>{{ rand_word }}:</h2>
            <form action="{% url 'wordfib:add_def' %}" method="post">
            {% csrf_token %}
                <input type="hidden" value="{{ user.user }}" name="user"/>
                <input type="hidden" value="{{ rand_word }}" name="word"/>
                <textarea  id="inputHelpBlock" class="form-control" rows="4" cols="50" name="definition" autofocus placeholder="Enter definition here"></textarea>
                <span id="helpBlock" class="help-block"><ol>
                    <li>You can make an obviously fake, yet incredibly humorous definition, but realize that this approach should be used as sparingly as salt and sarcasm.</li>
                    <li>A dry and convincing definition will net you good points, but may be boring.</li>
                    <li>A subtle combination of #1 and #2 will entertain but still win votes!</li>
                    <li>Commas, apostrophes, and periods are the only punctuation allowed.</li></span>
                </br>
                <p>
                    <input type="submit" class="btn btn-primary btn-lg" value="Enter Definition">
                </p>
            </form>
        </div>
    </div>
    </div>
    </body>
</html>

wordfib/templates/wordfibbd.html
{% include 'header.html' %}
        <div>
            <p>{{ user.user }}!! You are awarded no points, and may God have mercy on your soul.</p>
            <p>You just got WORDFIBBD by {{ author.author }}!</p>
            <p>Your current score is {{ current_score }}.</p>
            <p>If you want to try and actually <em>increase</em> your score, you can submit a definition to try and wordfib others!<p>
        </div>
{% include 'word_def_footer.html' %}